import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
  ssl: { rejectUnauthorized: false },
});
const prisma = new PrismaClient({ adapter });

async function main() {
  // Create super admin
  const adminPassword = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { email: "admin@destill.com" },
    update: {},
    create: {
      name: "Super Admin",
      email: "admin@destill.com",
      hashedPassword: adminPassword,
      role: "SUPER_ADMIN",
    },
  });

  // Create default categories with images
  const categories = [
    {
      name: "Pain Relief",
      slug: "pain-relief",
      description: "Pain relief medications and analgesics",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Antibiotics",
      slug: "antibiotics",
      description: "Antibiotic medications for bacterial infections",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Vitamins & Supplements",
      slug: "vitamins-supplements",
      description: "Vitamins, minerals, and dietary supplements",
      image: "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "First Aid",
      slug: "first-aid",
      description: "First aid supplies and emergency medications",
      image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Skin Care",
      slug: "skin-care",
      description: "Dermatological products and skin care treatments",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Cold & Flu",
      slug: "cold-flu",
      description: "Cold, flu, cough and congestion medications",
      image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Digestive Health",
      slug: "digestive-health",
      description: "Digestive health and stomach medications",
      image: "https://images.unsplash.com/photo-1505576399279-0a06b2f2c56e?q=80&w=800&auto=format&fit=crop",
    },
    {
      name: "Eye & Ear Care",
      slug: "eye-ear-care",
      description: "Eye drops, ear drops, and related products",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=800&auto=format&fit=crop",
    },
  ];

  const categoryMap: Record<string, string> = {};
  for (const category of categories) {
    const cat = await prisma.category.upsert({
      where: { slug: category.slug },
      update: { image: category.image, description: category.description },
      create: category,
    });
    categoryMap[category.slug] = cat.id;
  }

  // Create site settings
  const existingSettings = await prisma.siteSettings.findFirst();
  if (!existingSettings) {
    await prisma.siteSettings.create({
      data: {
        siteName: "De-Still Pharmacy",
        tagline: "Your trusted online pharmacy",
        currency: "NGN",
        deliveryFee: 1500,
      },
    });
  }

  // ── Sample Products (52 products across all categories) ──

  const products: {
    name: string;
    slug: string;
    description: string;
    shortDescription: string;
    price: number;
    compareAtPrice?: number;
    stock: number;
    categorySlug: string;
    isPublished: boolean;
    isFeatured?: boolean;
    requiresPrescription?: boolean;
    manufacturer: string;
    activeIngredients?: string;
    dosageInfo?: string;
    sideEffects?: string;
    image: string;
  }[] = [
    // ── Pain Relief (7) ──
    {
      name: "Paracetamol 500mg Tablets",
      slug: "paracetamol-500mg",
      description: "Paracetamol is a widely used pain reliever and fever reducer. Each tablet contains 500mg of paracetamol for effective relief from headaches, toothaches, backaches, and fever.",
      shortDescription: "Fast-acting pain relief and fever reducer",
      price: 350,
      stock: 200,
      categorySlug: "pain-relief",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Emzor Pharmaceuticals",
      activeIngredients: "Paracetamol 500mg",
      dosageInfo: "Adults: 1-2 tablets every 4-6 hours. Maximum 8 tablets in 24 hours.",
      sideEffects: "Rare: skin rash, blood disorders. Seek medical advice if symptoms persist.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Ibuprofen 400mg Tablets",
      slug: "ibuprofen-400mg",
      description: "Ibuprofen provides effective relief from pain, inflammation, and fever. Suitable for headaches, dental pain, menstrual cramps, muscular pain, and cold symptoms.",
      shortDescription: "Anti-inflammatory pain relief",
      price: 500,
      stock: 150,
      categorySlug: "pain-relief",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Swiss Pharma",
      activeIngredients: "Ibuprofen 400mg",
      dosageInfo: "Adults: 1 tablet every 6-8 hours with food. Maximum 3 tablets daily.",
      sideEffects: "May cause stomach upset, nausea. Take with food to reduce stomach irritation.",
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Diclofenac 50mg Tablets",
      slug: "diclofenac-50mg",
      description: "Diclofenac sodium is a potent non-steroidal anti-inflammatory drug (NSAID) used for the treatment of pain, inflammation, and stiffness caused by various conditions.",
      shortDescription: "Strong anti-inflammatory for joint and muscle pain",
      price: 750,
      stock: 100,
      categorySlug: "pain-relief",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Fidson Healthcare",
      activeIngredients: "Diclofenac Sodium 50mg",
      dosageInfo: "Adults: 1 tablet 2-3 times daily with food.",
      sideEffects: "Stomach pain, nausea, dizziness. Not suitable for patients with peptic ulcer.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Aspirin 300mg Tablets",
      slug: "aspirin-300mg",
      description: "Aspirin for the relief of mild to moderate pain including headache, toothache, and period pain. Also used to reduce fever and inflammation.",
      shortDescription: "Classic pain and fever relief",
      price: 300,
      stock: 180,
      categorySlug: "pain-relief",
      isPublished: true,
      manufacturer: "Bayer",
      activeIngredients: "Acetylsalicylic Acid 300mg",
      dosageInfo: "Adults: 1-2 tablets every 4-6 hours as needed. Maximum 12 tablets in 24 hours.",
      sideEffects: "May cause stomach irritation. Not suitable for children under 16.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Tramadol 50mg Capsules",
      slug: "tramadol-50mg",
      description: "Tramadol is a strong pain reliever used to treat moderate to severe pain. This is a prescription-only medication that works by changing how your brain senses pain.",
      shortDescription: "Prescription strength pain relief",
      price: 1200,
      stock: 50,
      categorySlug: "pain-relief",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Getz Pharma",
      activeIngredients: "Tramadol Hydrochloride 50mg",
      dosageInfo: "As directed by physician. Usually 1 capsule every 4-6 hours.",
      sideEffects: "Dizziness, nausea, constipation, headache. May cause drowsiness.",
      image: "https://images.unsplash.com/photo-1559757175-7cb036fa6709?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Voltaren Emulgel 50g",
      slug: "voltaren-emulgel-50g",
      description: "Voltaren Emulgel contains diclofenac diethylamine for topical relief of pain and inflammation. Apply directly to the affected area for targeted pain relief.",
      shortDescription: "Topical gel for muscle and joint pain",
      price: 2500,
      compareAtPrice: 3200,
      stock: 80,
      categorySlug: "pain-relief",
      isPublished: true,
      isFeatured: true,
      manufacturer: "GSK",
      activeIngredients: "Diclofenac Diethylamine 1.16%",
      dosageInfo: "Apply 2-4g to affected area 3-4 times daily. Rub in gently.",
      sideEffects: "Skin irritation at application site. Avoid broken skin.",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Muscle Rub Heat Cream 60g",
      slug: "muscle-rub-heat-cream",
      description: "Deep heat muscle rub cream provides warming relief for muscular aches, pains, and stiffness. Ideal for sports injuries and general muscle tension.",
      shortDescription: "Warming muscle relief cream",
      price: 1800,
      stock: 90,
      categorySlug: "pain-relief",
      isPublished: true,
      manufacturer: "Mentholatum",
      activeIngredients: "Methyl Salicylate, Menthol",
      dosageInfo: "Apply to affected area and massage gently. Use 2-3 times daily.",
      sideEffects: "Skin irritation in sensitive individuals. For external use only.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    },

    // ── Antibiotics (7) ──
    {
      name: "Amoxicillin 500mg Capsules",
      slug: "amoxicillin-500mg",
      description: "Amoxicillin is a broad-spectrum antibiotic used to treat various bacterial infections including respiratory tract infections, urinary tract infections, and skin infections.",
      shortDescription: "Broad-spectrum antibiotic",
      price: 1500,
      stock: 120,
      categorySlug: "antibiotics",
      isPublished: true,
      isFeatured: true,
      requiresPrescription: true,
      manufacturer: "Fidson Healthcare",
      activeIngredients: "Amoxicillin Trihydrate 500mg",
      dosageInfo: "Adults: 1 capsule 3 times daily for 5-7 days or as directed by physician.",
      sideEffects: "Diarrhea, nausea, skin rash. Discontinue if allergic reaction occurs.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Azithromycin 250mg Tablets",
      slug: "azithromycin-250mg",
      description: "Azithromycin is a macrolide antibiotic effective against a wide range of bacterial infections. Often prescribed for respiratory infections, skin infections, and STIs.",
      shortDescription: "Macrolide antibiotic for infections",
      price: 2000,
      stock: 90,
      categorySlug: "antibiotics",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Pfizer",
      activeIngredients: "Azithromycin Dihydrate 250mg",
      dosageInfo: "Usually 2 tablets on day 1, then 1 tablet daily for 4 days.",
      sideEffects: "Stomach upset, diarrhea, nausea. Complete the full course.",
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Ciprofloxacin 500mg Tablets",
      slug: "ciprofloxacin-500mg",
      description: "Ciprofloxacin is a fluoroquinolone antibiotic used for treating urinary tract infections, respiratory infections, and gastrointestinal infections.",
      shortDescription: "Fluoroquinolone antibiotic",
      price: 1800,
      stock: 75,
      categorySlug: "antibiotics",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Emzor Pharmaceuticals",
      activeIngredients: "Ciprofloxacin 500mg",
      dosageInfo: "1 tablet twice daily for 7-14 days as directed by doctor.",
      sideEffects: "Nausea, diarrhea, headache. Avoid dairy products close to dosing time.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Metronidazole 400mg Tablets",
      slug: "metronidazole-400mg",
      description: "Metronidazole is an antibiotic and antiprotozoal medication used to treat bacterial and parasitic infections including dental infections and stomach ulcers.",
      shortDescription: "Antibiotic for bacterial and parasitic infections",
      price: 800,
      stock: 130,
      categorySlug: "antibiotics",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "May & Baker",
      activeIngredients: "Metronidazole 400mg",
      dosageInfo: "1 tablet 3 times daily for 7 days or as prescribed.",
      sideEffects: "Metallic taste, nausea. Avoid alcohol during treatment.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Augmentin 625mg Tablets",
      slug: "augmentin-625mg",
      description: "Augmentin combines amoxicillin with clavulanic acid for enhanced antibacterial activity against resistant bacteria. Used for severe infections.",
      shortDescription: "Enhanced antibiotic combination",
      price: 3500,
      compareAtPrice: 4200,
      stock: 60,
      categorySlug: "antibiotics",
      isPublished: true,
      isFeatured: true,
      requiresPrescription: true,
      manufacturer: "GSK",
      activeIngredients: "Amoxicillin 500mg + Clavulanic Acid 125mg",
      dosageInfo: "1 tablet twice daily with meals for 5-7 days.",
      sideEffects: "Diarrhea, nausea, vomiting, skin rash.",
      image: "https://images.unsplash.com/photo-1559757175-7cb036fa6709?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Doxycycline 100mg Capsules",
      slug: "doxycycline-100mg",
      description: "Doxycycline is a tetracycline antibiotic used for acne, respiratory infections, urinary tract infections, and malaria prophylaxis.",
      shortDescription: "Versatile tetracycline antibiotic",
      price: 1200,
      stock: 100,
      categorySlug: "antibiotics",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Ranbaxy",
      activeIngredients: "Doxycycline Hyclate 100mg",
      dosageInfo: "1 capsule twice daily for 7 days. Take with plenty of water.",
      sideEffects: "Photosensitivity, nausea. Avoid sun exposure.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Erythromycin 250mg Tablets",
      slug: "erythromycin-250mg",
      description: "Erythromycin is a macrolide antibiotic suitable for patients allergic to penicillin. Treats respiratory, skin, and soft tissue infections.",
      shortDescription: "Penicillin-alternative antibiotic",
      price: 1400,
      stock: 85,
      categorySlug: "antibiotics",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Emzor Pharmaceuticals",
      activeIngredients: "Erythromycin Stearate 250mg",
      dosageInfo: "1-2 tablets 4 times daily before meals.",
      sideEffects: "Stomach cramps, nausea, diarrhea.",
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?q=80&w=600&auto=format&fit=crop",
    },

    // ── Vitamins & Supplements (8) ──
    {
      name: "Vitamin C 1000mg Effervescent",
      slug: "vitamin-c-1000mg",
      description: "High-strength Vitamin C effervescent tablets for immune support. Dissolve in water for a refreshing orange-flavored drink packed with antioxidants.",
      shortDescription: "Immune-boosting Vitamin C tablets",
      price: 2500,
      stock: 200,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Swiss Pharma",
      activeIngredients: "Ascorbic Acid 1000mg",
      dosageInfo: "1 tablet dissolved in a glass of water daily.",
      image: "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Multivitamin Complete Daily",
      slug: "multivitamin-complete",
      description: "Complete daily multivitamin with essential vitamins and minerals. Supports overall health, energy levels, and immune function.",
      shortDescription: "Complete daily nutrition support",
      price: 3500,
      compareAtPrice: 4500,
      stock: 150,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Nature's Bounty",
      activeIngredients: "Vitamins A, B-complex, C, D, E, Iron, Zinc, Calcium",
      dosageInfo: "1 tablet daily with meals.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Omega-3 Fish Oil 1000mg",
      slug: "omega-3-fish-oil",
      description: "Premium fish oil capsules rich in EPA and DHA omega-3 fatty acids. Supports heart health, brain function, and reduces inflammation.",
      shortDescription: "Heart and brain health support",
      price: 4500,
      stock: 120,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Seven Seas",
      activeIngredients: "Fish Oil 1000mg (EPA 180mg, DHA 120mg)",
      dosageInfo: "1-2 capsules daily with meals.",
      image: "https://images.unsplash.com/photo-1559757175-7cb036fa6709?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Vitamin D3 5000 IU",
      slug: "vitamin-d3-5000iu",
      description: "High-strength Vitamin D3 for bone health and immune support. Essential for calcium absorption and maintaining strong bones and teeth.",
      shortDescription: "Sunshine vitamin for bone health",
      price: 3000,
      stock: 100,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Vitabiotics",
      activeIngredients: "Cholecalciferol (Vitamin D3) 5000 IU",
      dosageInfo: "1 tablet daily with food.",
      image: "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Iron + Folic Acid Tablets",
      slug: "iron-folic-acid",
      description: "Iron supplement with folic acid for the prevention and treatment of iron deficiency anemia. Essential during pregnancy and for women of childbearing age.",
      shortDescription: "Anemia prevention and treatment",
      price: 1500,
      stock: 180,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Emzor Pharmaceuticals",
      activeIngredients: "Ferrous Sulphate 200mg, Folic Acid 0.5mg",
      dosageInfo: "1 tablet daily, preferably on empty stomach.",
      sideEffects: "Dark stool, constipation. Take with orange juice for better absorption.",
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Zinc 50mg Tablets",
      slug: "zinc-50mg",
      description: "Zinc supplement for immune support, wound healing, and skin health. Zinc plays a vital role in numerous enzymatic processes in the body.",
      shortDescription: "Immune and skin support",
      price: 2000,
      stock: 140,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Nature Made",
      activeIngredients: "Zinc Gluconate 50mg",
      dosageInfo: "1 tablet daily with food.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Calcium + Vitamin D Tablets",
      slug: "calcium-vitamin-d",
      description: "Calcium and Vitamin D combination for strong bones and teeth. Helps prevent osteoporosis and supports muscle function.",
      shortDescription: "Bone strength formula",
      price: 2800,
      stock: 110,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Vitabiotics",
      activeIngredients: "Calcium Carbonate 600mg, Vitamin D3 400 IU",
      dosageInfo: "1 tablet twice daily with meals.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Vitamin B Complex Tablets",
      slug: "vitamin-b-complex",
      description: "Complete B-vitamin complex for energy metabolism and nervous system support. Contains all essential B vitamins in optimal doses.",
      shortDescription: "Energy and nervous system support",
      price: 2200,
      stock: 130,
      categorySlug: "vitamins-supplements",
      isPublished: true,
      manufacturer: "Swiss Pharma",
      activeIngredients: "Vitamins B1, B2, B3, B5, B6, B7, B9, B12",
      dosageInfo: "1 tablet daily with breakfast.",
      image: "https://images.unsplash.com/photo-1556227702-d1e4e7b5c232?q=80&w=600&auto=format&fit=crop",
    },

    // ── First Aid (6) ──
    {
      name: "Antiseptic Wound Wash 250ml",
      slug: "antiseptic-wound-wash",
      description: "Gentle antiseptic wound wash solution for cleaning cuts, grazes, and minor wounds. Kills bacteria to prevent infection and promote healing.",
      shortDescription: "Wound cleaning antiseptic",
      price: 1200,
      stock: 100,
      categorySlug: "first-aid",
      isPublished: true,
      manufacturer: "Dettol",
      activeIngredients: "Chlorhexidine Gluconate 0.05%",
      dosageInfo: "Apply directly to wound or use with cotton wool. Clean wound 2-3 times daily.",
      image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Adhesive Bandages Assorted 50pk",
      slug: "adhesive-bandages-50pk",
      description: "Box of 50 assorted adhesive bandages in various sizes. Flexible fabric material that stays in place. Ideal for minor cuts and scrapes.",
      shortDescription: "Assorted plasters for minor wounds",
      price: 800,
      stock: 200,
      categorySlug: "first-aid",
      isPublished: true,
      manufacturer: "Band-Aid",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "First Aid Kit Comprehensive",
      slug: "first-aid-kit-comprehensive",
      description: "Comprehensive first aid kit containing bandages, antiseptic wipes, gauze pads, medical tape, scissors, gloves, and essential medications for home or travel.",
      shortDescription: "Complete emergency first aid kit",
      price: 8500,
      compareAtPrice: 10000,
      stock: 40,
      categorySlug: "first-aid",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Red Cross",
      image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Hydrogen Peroxide 3% 200ml",
      slug: "hydrogen-peroxide-3pct",
      description: "Hydrogen peroxide solution for wound cleaning and disinfection. Helps remove dead tissue and prevent infection in minor cuts and abrasions.",
      shortDescription: "Wound disinfectant solution",
      price: 600,
      stock: 150,
      categorySlug: "first-aid",
      isPublished: true,
      manufacturer: "General Healthcare",
      activeIngredients: "Hydrogen Peroxide 3%",
      dosageInfo: "Apply directly to wound using cotton wool. Do not use on deep wounds.",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Elastic Crepe Bandage 10cm",
      slug: "elastic-crepe-bandage-10cm",
      description: "Reusable elastic crepe bandage for support and compression. Ideal for sprains, strains, and securing wound dressings.",
      shortDescription: "Compression support bandage",
      price: 500,
      stock: 120,
      categorySlug: "first-aid",
      isPublished: true,
      manufacturer: "Medicare",
      image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Digital Thermometer",
      slug: "digital-thermometer",
      description: "Accurate digital thermometer with fast reading time. Features fever alarm, memory recall, and flexible tip for comfortable use.",
      shortDescription: "Fast and accurate temperature reading",
      price: 2500,
      stock: 60,
      categorySlug: "first-aid",
      isPublished: true,
      manufacturer: "Omron",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },

    // ── Skin Care (6) ──
    {
      name: "Hydrocortisone Cream 1% 15g",
      slug: "hydrocortisone-cream-1pct",
      description: "Mild corticosteroid cream for the relief of itching, redness, and inflammation associated with eczema, dermatitis, insect bites, and minor skin irritations.",
      shortDescription: "Anti-itch and anti-inflammatory cream",
      price: 1500,
      stock: 80,
      categorySlug: "skin-care",
      isPublished: true,
      manufacturer: "GSK",
      activeIngredients: "Hydrocortisone 1%",
      dosageInfo: "Apply a thin layer to affected area 1-2 times daily. Do not use for more than 7 days.",
      sideEffects: "Skin thinning with prolonged use. Avoid use on face.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Clotrimazole Antifungal Cream 20g",
      slug: "clotrimazole-cream",
      description: "Antifungal cream for the treatment of athlete's foot, ringworm, jock itch, and other fungal skin infections. Provides relief from itching and burning.",
      shortDescription: "Antifungal treatment cream",
      price: 1200,
      stock: 90,
      categorySlug: "skin-care",
      isPublished: true,
      manufacturer: "Bayer",
      activeIngredients: "Clotrimazole 1%",
      dosageInfo: "Apply to affected area 2-3 times daily for 2-4 weeks.",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Sunscreen SPF 50+ 100ml",
      slug: "sunscreen-spf50",
      description: "High protection broad-spectrum sunscreen that shields against UVA and UVB rays. Lightweight, non-greasy formula suitable for all skin types.",
      shortDescription: "High SPF sun protection",
      price: 4500,
      compareAtPrice: 5500,
      stock: 70,
      categorySlug: "skin-care",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Neutrogena",
      activeIngredients: "Avobenzone, Homosalate, Octisalate",
      dosageInfo: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Calamine Lotion 200ml",
      slug: "calamine-lotion",
      description: "Soothing calamine lotion for the relief of sunburn, insect bites, chicken pox, and other mild skin irritations. Provides cooling relief.",
      shortDescription: "Soothing skin lotion",
      price: 900,
      stock: 110,
      categorySlug: "skin-care",
      isPublished: true,
      manufacturer: "Johnson & Johnson",
      activeIngredients: "Calamine, Zinc Oxide",
      dosageInfo: "Shake well. Apply to affected area as needed.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Acne Treatment Gel 30g",
      slug: "acne-treatment-gel",
      description: "Benzoyl peroxide gel for the treatment of mild to moderate acne. Kills acne-causing bacteria and helps unclog pores.",
      shortDescription: "Clear skin acne treatment",
      price: 2800,
      stock: 65,
      categorySlug: "skin-care",
      isPublished: true,
      manufacturer: "La Roche-Posay",
      activeIngredients: "Benzoyl Peroxide 5%",
      dosageInfo: "Apply a thin layer to clean, dry skin once daily.",
      sideEffects: "Dryness, peeling, redness. Use sunscreen during treatment.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Petroleum Jelly 250g",
      slug: "petroleum-jelly-250g",
      description: "Pure petroleum jelly for skin protection and moisture retention. Ideal for dry, cracked skin, minor burns, and as a skin barrier.",
      shortDescription: "Skin protectant and moisturizer",
      price: 700,
      stock: 200,
      categorySlug: "skin-care",
      isPublished: true,
      manufacturer: "Vaseline",
      dosageInfo: "Apply as needed to dry or irritated skin.",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },

    // ── Cold & Flu (6) ──
    {
      name: "Cold & Flu Day/Night Capsules",
      slug: "cold-flu-day-night",
      description: "Combination pack with daytime capsules for symptom relief without drowsiness and nighttime capsules to help you rest while fighting cold and flu symptoms.",
      shortDescription: "24-hour cold and flu relief",
      price: 2500,
      stock: 100,
      categorySlug: "cold-flu",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Lemsip",
      activeIngredients: "Paracetamol, Phenylephrine, Chlorphenamine (night)",
      dosageInfo: "Day: 2 capsules every 4-6 hours. Night: 2 capsules at bedtime.",
      sideEffects: "Night capsules may cause drowsiness. Do not drive after taking.",
      image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Cough Syrup Adult 150ml",
      slug: "cough-syrup-adult",
      description: "Effective cough suppressant syrup for dry and tickly coughs. Soothes the throat and provides up to 8 hours of relief.",
      shortDescription: "Dry cough relief syrup",
      price: 1800,
      stock: 90,
      categorySlug: "cold-flu",
      isPublished: true,
      manufacturer: "Benylin",
      activeIngredients: "Dextromethorphan 15mg/5ml",
      dosageInfo: "Adults: 10ml every 4-6 hours. Maximum 4 doses in 24 hours.",
      sideEffects: "Drowsiness, dizziness. Avoid alcohol.",
      image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Nasal Decongestant Spray 15ml",
      slug: "nasal-decongestant-spray",
      description: "Fast-acting nasal decongestant spray that provides relief from blocked nose caused by cold, flu, sinusitis, and allergies.",
      shortDescription: "Blocked nose relief spray",
      price: 1500,
      stock: 80,
      categorySlug: "cold-flu",
      isPublished: true,
      manufacturer: "Otrivine",
      activeIngredients: "Xylometazoline 0.1%",
      dosageInfo: "1-2 sprays per nostril 2-3 times daily. Do not use for more than 7 days.",
      sideEffects: "Temporary stinging, rebound congestion with prolonged use.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Throat Lozenges Menthol 24pk",
      slug: "throat-lozenges-menthol",
      description: "Soothing menthol throat lozenges for relief of sore throats and coughs. Provides a cooling sensation and temporary pain relief.",
      shortDescription: "Soothing sore throat relief",
      price: 800,
      stock: 200,
      categorySlug: "cold-flu",
      isPublished: true,
      manufacturer: "Strepsils",
      activeIngredients: "Menthol, Eucalyptus Oil",
      dosageInfo: "Dissolve 1 lozenge slowly in the mouth every 2-3 hours as needed.",
      image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Flu Hot Drink Sachets 10pk",
      slug: "flu-hot-drink-sachets",
      description: "Lemon-flavored hot drink sachets for flu symptom relief. Contains paracetamol to reduce fever and ease aches, plus vitamin C for immune support.",
      shortDescription: "Hot flu relief drink",
      price: 2000,
      stock: 120,
      categorySlug: "cold-flu",
      isPublished: true,
      manufacturer: "Lemsip",
      activeIngredients: "Paracetamol 1000mg, Vitamin C 40mg, Phenylephrine 12.2mg",
      dosageInfo: "Dissolve 1 sachet in hot water. Take every 4-6 hours. Max 4 sachets daily.",
      image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Chest Rub Vapour Balm 50g",
      slug: "chest-rub-vapour-balm",
      description: "Medicated vapour rub for relief of nasal congestion and muscular aches due to cold and flu. Apply to chest and throat for soothing vapours.",
      shortDescription: "Decongestant chest rub",
      price: 1200,
      stock: 90,
      categorySlug: "cold-flu",
      isPublished: true,
      manufacturer: "Vicks",
      activeIngredients: "Camphor, Menthol, Eucalyptus Oil",
      dosageInfo: "Rub on chest, throat, and back. Can also be used in hot water for steam inhalation.",
      image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=600&auto=format&fit=crop",
    },

    // ── Digestive Health (6) ──
    {
      name: "Omeprazole 20mg Capsules",
      slug: "omeprazole-20mg",
      description: "Proton pump inhibitor for the treatment of heartburn, acid reflux, and stomach ulcers. Reduces stomach acid production for long-lasting relief.",
      shortDescription: "Acid reflux and ulcer treatment",
      price: 1500,
      stock: 100,
      categorySlug: "digestive-health",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "AstraZeneca",
      activeIngredients: "Omeprazole 20mg",
      dosageInfo: "1 capsule daily, 30 minutes before breakfast.",
      sideEffects: "Headache, stomach pain, diarrhea.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Oral Rehydration Salts 20 Sachets",
      slug: "oral-rehydration-salts",
      description: "WHO-formula oral rehydration salts for the prevention and treatment of dehydration due to diarrhea. Essential for both children and adults.",
      shortDescription: "Dehydration prevention and treatment",
      price: 500,
      stock: 300,
      categorySlug: "digestive-health",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Emzor Pharmaceuticals",
      activeIngredients: "Sodium Chloride, Potassium Chloride, Sodium Citrate, Glucose",
      dosageInfo: "Dissolve 1 sachet in 1 litre of clean water. Sip frequently.",
      image: "https://images.unsplash.com/photo-1505576399279-0a06b2f2c56e?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Antacid Suspension 200ml",
      slug: "antacid-suspension",
      description: "Fast-acting liquid antacid for relief of heartburn, indigestion, and acid stomach. Neutralizes excess stomach acid within minutes.",
      shortDescription: "Fast heartburn relief",
      price: 1200,
      stock: 110,
      categorySlug: "digestive-health",
      isPublished: true,
      manufacturer: "Gaviscon",
      activeIngredients: "Aluminium Hydroxide, Magnesium Hydroxide",
      dosageInfo: "10-20ml after meals and at bedtime. Shake well before use.",
      image: "https://images.unsplash.com/photo-1505576399279-0a06b2f2c56e?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Loperamide 2mg Capsules",
      slug: "loperamide-2mg",
      description: "Anti-diarrheal medication that slows gut movement to reduce the frequency of diarrhea. Provides rapid relief for acute and chronic diarrhea.",
      shortDescription: "Diarrhea relief capsules",
      price: 800,
      stock: 130,
      categorySlug: "digestive-health",
      isPublished: true,
      manufacturer: "Imodium",
      activeIngredients: "Loperamide Hydrochloride 2mg",
      dosageInfo: "Initial dose: 2 capsules, then 1 after each loose stool. Max 8 daily.",
      sideEffects: "Constipation, abdominal cramps, bloating.",
      image: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Probiotics Capsules 30pk",
      slug: "probiotics-capsules",
      description: "Live probiotic cultures to support digestive health and restore gut flora balance. Contains multiple strains of beneficial bacteria.",
      shortDescription: "Gut health probiotic supplement",
      price: 4500,
      compareAtPrice: 5500,
      stock: 60,
      categorySlug: "digestive-health",
      isPublished: true,
      manufacturer: "Bio-Kult",
      activeIngredients: "14 strains of live bacteria, 2 billion CFU",
      dosageInfo: "1-2 capsules daily with food.",
      image: "https://images.unsplash.com/photo-1559757175-7cb036fa6709?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Activated Charcoal 250mg Tablets",
      slug: "activated-charcoal-250mg",
      description: "Activated charcoal tablets for relief of flatulence, bloating, and stomach discomfort. Absorbs excess gas and toxins in the digestive system.",
      shortDescription: "Gas and bloating relief",
      price: 1000,
      stock: 140,
      categorySlug: "digestive-health",
      isPublished: true,
      manufacturer: "General Healthcare",
      activeIngredients: "Activated Charcoal 250mg",
      dosageInfo: "2 tablets after meals or when symptoms occur.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=600&auto=format&fit=crop",
    },

    // ── Eye & Ear Care (6) ──
    {
      name: "Artificial Tears Eye Drops 10ml",
      slug: "artificial-tears-eye-drops",
      description: "Lubricating eye drops for relief of dry, tired, and irritated eyes. Provides long-lasting moisture and comfort. Safe for contact lens wearers.",
      shortDescription: "Dry eye relief drops",
      price: 2000,
      stock: 80,
      categorySlug: "eye-ear-care",
      isPublished: true,
      isFeatured: true,
      manufacturer: "Alcon",
      activeIngredients: "Sodium Hyaluronate 0.1%",
      dosageInfo: "1-2 drops in each eye as needed throughout the day.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Antibiotic Eye Drops 5ml",
      slug: "antibiotic-eye-drops",
      description: "Chloramphenicol eye drops for the treatment of bacterial conjunctivitis (pink eye) and other bacterial eye infections.",
      shortDescription: "Bacterial eye infection treatment",
      price: 1500,
      stock: 70,
      categorySlug: "eye-ear-care",
      isPublished: true,
      requiresPrescription: true,
      manufacturer: "Bausch + Lomb",
      activeIngredients: "Chloramphenicol 0.5%",
      dosageInfo: "1 drop in affected eye every 2 hours for 2 days, then every 4 hours for 5 days.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Ear Wax Removal Drops 10ml",
      slug: "ear-wax-removal-drops",
      description: "Gentle ear drops that soften and help remove excess ear wax. Contains urea hydrogen peroxide for effective wax dissolution.",
      shortDescription: "Ear wax softening drops",
      price: 1200,
      stock: 60,
      categorySlug: "eye-ear-care",
      isPublished: true,
      manufacturer: "Otex",
      activeIngredients: "Urea Hydrogen Peroxide 5%",
      dosageInfo: "Tilt head, apply 5 drops in ear. Keep tilted for few minutes. Use 3-4 days.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Allergy Eye Drops 10ml",
      slug: "allergy-eye-drops",
      description: "Antihistamine eye drops for the relief of itchy, watery eyes caused by allergies. Provides fast relief from hay fever and allergic conjunctivitis symptoms.",
      shortDescription: "Allergy relief eye drops",
      price: 2500,
      stock: 55,
      categorySlug: "eye-ear-care",
      isPublished: true,
      manufacturer: "Optrex",
      activeIngredients: "Sodium Cromoglicate 2%",
      dosageInfo: "1-2 drops in each eye 4 times daily.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Eye Wash Solution 300ml",
      slug: "eye-wash-solution",
      description: "Sterile eye wash solution for flushing and cleansing eyes. Removes dust, pollen, and other foreign particles. Essential for first aid kits.",
      shortDescription: "Sterile eye cleansing solution",
      price: 1800,
      stock: 50,
      categorySlug: "eye-ear-care",
      isPublished: true,
      manufacturer: "Optrex",
      dosageInfo: "Use eye bath provided. Fill with solution and bathe eye for 1-2 minutes.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
    {
      name: "Swimmer's Ear Drops 10ml",
      slug: "swimmers-ear-drops",
      description: "Preventive ear drops for swimmer's ear (otitis externa). Dries excess water and prevents bacterial growth after swimming or bathing.",
      shortDescription: "Swimmer's ear prevention",
      price: 1500,
      stock: 45,
      categorySlug: "eye-ear-care",
      isPublished: true,
      manufacturer: "Aqua Ear",
      activeIngredients: "Isopropyl Alcohol, Acetic Acid",
      dosageInfo: "4-5 drops in each ear after swimming. Tilt head to allow drainage.",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=600&auto=format&fit=crop",
    },
  ];

  // Create products (skip existing)
  let created = 0;
  for (const product of products) {
    const categoryId = categoryMap[product.categorySlug];
    if (!categoryId) {
      console.warn(`Category not found for slug: ${product.categorySlug}`);
      continue;
    }

    const existing = await prisma.product.findUnique({ where: { slug: product.slug } });
    if (existing) continue;

    const { categorySlug, image, ...data } = product;

    const createdProduct = await prisma.product.create({
      data: {
        ...data,
        categoryId,
        requiresPrescription: data.requiresPrescription ?? false,
        isFeatured: data.isFeatured ?? false,
      },
    });

    if (image) {
      await prisma.productImage.create({
        data: {
          url: image,
          alt: product.name,
          position: 0,
          productId: createdProduct.id,
        },
      });
    }

    created++;
  }

  console.log(`Seed completed: ${created} products created, ${categories.length} categories with images`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
